version: '2'
services:
    midapp2-app:
        image: midapp2
        external_links:
            - midapp2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/midapp2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    midapp2-mysql:
        extends:
            file: mysql.yml
            service: midapp2-mysql
